select * from book;
update book set autor_last_name = 'КУПРІН' where id in(1,9);
select count(*) from book where not awards = 'null';
select * from book where pages = (select min(pages) from book );
select max(pages) FROM book;
select avg(price) from book;
select count(*) from book where category ='роман';
select min(price) FROM book;
select * from book where price = (select min(price) FROM book);
select id, name_book, category, round(price, 4) as rounded_price from book order by name_book;
select * from book order by publication_date limit 5,5;
select * from book order by publication_date limit 10,6;
select * from book where price like '%2';
select * from book where category like '_ом%';
select * from book where pages like '%3%';
select * from book where price between  1.50 and 120.2 ;
select * from book where price not between  200 and 600;
delete from book where id = 1;
delete from book where name_book ='otello';
delete from book where isbn ='ps-344';
